using Shr.ZipCodeValidator.Common;
using Shr.ZipCodeValidator.CountryValidators;
using Shr.ZipCodeValidator.ValidatorFactories;
using Shr.ZipCodeValidator.ValidatorStrategies;
using System.Collections.Generic;

namespace Shr.ZipCodeValidator.Tests
{
    internal static class MockInstance
    {
        internal static IValidatorStrategy<List<string>, string> _strategy;
        internal static List<ICountryZipCodeValidator> countryValidators;
        internal static IValidatorFactory<ICountryZipCodeValidator, CountryCode> factory;

        static MockInstance()
        {
            _strategy = new RegexValidatorStrategy(true);

            countryValidators = new List<ICountryZipCodeValidator>
            {
                new ADZipCodeValidator(_strategy),
                new AMZipCodeValidator(_strategy),
                new ARZipCodeValidator(_strategy),
                new ASZipCodeValidator(_strategy),
                new ATZipCodeValidator(_strategy),
                new AUZipCodeValidator(_strategy),
                new AXZipCodeValidator(_strategy),
                new AZZipCodeValidator(_strategy),
                new BAZipCodeValidator(_strategy),
                new BBZipCodeValidator(_strategy),
                new BDZipCodeValidator(_strategy),
                new BEZipCodeValidator(_strategy),
                new BGZipCodeValidator(_strategy),
                new BHZipCodeValidator(_strategy),
                new BMZipCodeValidator(_strategy),
                new BNZipCodeValidator(_strategy),
                new BRZipCodeValidator(_strategy),
                new BYZipCodeValidator(_strategy),
                new CAZipCodeValidator(_strategy),
                new CCZipCodeValidator(_strategy),
                new CHZipCodeValidator(_strategy),
                new CKZipCodeValidator(_strategy),
                new CLZipCodeValidator(_strategy),
                new CNZipCodeValidator(_strategy),
                new CRZipCodeValidator(_strategy),
                new CSZipCodeValidator(_strategy),
                new CVZipCodeValidator(_strategy),
                new CXZipCodeValidator(_strategy),
                new CYZipCodeValidator(_strategy),
                new CZZipCodeValidator(_strategy),
                new DEZipCodeValidator(_strategy),
                new DKZipCodeValidator(_strategy),
                new DOZipCodeValidator(_strategy),
                new DZZipCodeValidator(_strategy),
                new ECZipCodeValidator(_strategy),
                new EEZipCodeValidator(_strategy),
                new EGZipCodeValidator(_strategy),
                new ESZipCodeValidator(_strategy),
                new ETZipCodeValidator(_strategy),
                new FIZipCodeValidator(_strategy),
                new FKZipCodeValidator(_strategy),
                new FMZipCodeValidator(_strategy),
                new FOZipCodeValidator(_strategy),
                new FRZipCodeValidator(_strategy),
                new GBZipCodeValidator(_strategy),
                new GEZipCodeValidator(_strategy),
                new GFZipCodeValidator(_strategy),
                new GGZipCodeValidator(_strategy),
                new GLZipCodeValidator(_strategy),
                new GNZipCodeValidator(_strategy),
                new GPZipCodeValidator(_strategy),
                new GRZipCodeValidator(_strategy),
                new GSZipCodeValidator(_strategy),
                new GTZipCodeValidator(_strategy),
                new GUZipCodeValidator(_strategy),
                new GWZipCodeValidator(_strategy),
                new HMZipCodeValidator(_strategy),
                new HNZipCodeValidator(_strategy),
                new HRZipCodeValidator(_strategy),
                new HTZipCodeValidator(_strategy),
                new HUZipCodeValidator(_strategy),
                new IDZipCodeValidator(_strategy),
                new ILZipCodeValidator(_strategy),
                new IMZipCodeValidator(_strategy),
                new INZipCodeValidator(_strategy),
                new IOZipCodeValidator(_strategy),
                new IQZipCodeValidator(_strategy),
                new ISZipCodeValidator(_strategy),
                new ITZipCodeValidator(_strategy),
                new JEZipCodeValidator(_strategy),
                new JOZipCodeValidator(_strategy),
                new JPZipCodeValidator(_strategy),
                new KEZipCodeValidator(_strategy),
                new KGZipCodeValidator(_strategy),
                new KHZipCodeValidator(_strategy),
                new KRZipCodeValidator(_strategy),
                new KWZipCodeValidator(_strategy),
                new KZZipCodeValidator(_strategy),
                new LAZipCodeValidator(_strategy),
                new LBZipCodeValidator(_strategy),
                new LIZipCodeValidator(_strategy),
                new LKZipCodeValidator(_strategy),
                new LRZipCodeValidator(_strategy),
                new LSZipCodeValidator(_strategy),
                new LTZipCodeValidator(_strategy),
                new LUZipCodeValidator(_strategy),
                new LVZipCodeValidator(_strategy),
                new MAZipCodeValidator(_strategy),
                new MCZipCodeValidator(_strategy),
                new MDZipCodeValidator(_strategy),
                new MEZipCodeValidator(_strategy),
                new MGZipCodeValidator(_strategy),
                new MHZipCodeValidator(_strategy),
                new MKZipCodeValidator(_strategy),
                new MNZipCodeValidator(_strategy),
                new MPZipCodeValidator(_strategy),
                new MQZipCodeValidator(_strategy),
                new MTZipCodeValidator(_strategy),
                new MUZipCodeValidator(_strategy),
                new MVZipCodeValidator(_strategy),
                new MXZipCodeValidator(_strategy),
                new MYZipCodeValidator(_strategy),
                new NCZipCodeValidator(_strategy),
                new NEZipCodeValidator(_strategy),
                new NFZipCodeValidator(_strategy),
                new NGZipCodeValidator(_strategy),
                new NIZipCodeValidator(_strategy),
                new NLZipCodeValidator(_strategy),
                new NOZipCodeValidator(_strategy),
                new NPZipCodeValidator(_strategy),
                new NZZipCodeValidator(_strategy),
                new OMZipCodeValidator(_strategy),
                new PFZipCodeValidator(_strategy),
                new PGZipCodeValidator(_strategy),
                new PHZipCodeValidator(_strategy),
                new PKZipCodeValidator(_strategy),
                new PLZipCodeValidator(_strategy),
                new PMZipCodeValidator(_strategy),
                new PNZipCodeValidator(_strategy),
                new PRZipCodeValidator(_strategy),
                new PTZipCodeValidator(_strategy),
                new PWZipCodeValidator(_strategy),
                new PYZipCodeValidator(_strategy),
                new REZipCodeValidator(_strategy),
                new ROZipCodeValidator(_strategy),
                new RSZipCodeValidator(_strategy),
                new RUZipCodeValidator(_strategy),
                new SAZipCodeValidator(_strategy),
                new SEZipCodeValidator(_strategy),
                new SGZipCodeValidator(_strategy),
                new SHZipCodeValidator(_strategy),
                new SIZipCodeValidator(_strategy),
                new SJZipCodeValidator(_strategy),
                new SKZipCodeValidator(_strategy),
                new SMZipCodeValidator(_strategy),
                new SNZipCodeValidator(_strategy),
                new SOZipCodeValidator(_strategy),
                new SZZipCodeValidator(_strategy),
                new TCZipCodeValidator(_strategy),
                new THZipCodeValidator(_strategy),
                new TJZipCodeValidator(_strategy),
                new TMZipCodeValidator(_strategy),
                new TNZipCodeValidator(_strategy),
                new TRZipCodeValidator(_strategy),
                new TWZipCodeValidator(_strategy),
                new UAZipCodeValidator(_strategy),
                new USZipCodeValidator(_strategy),
                new UYZipCodeValidator(_strategy),
                new UZZipCodeValidator(_strategy),
                new VAZipCodeValidator(_strategy),
                new VEZipCodeValidator(_strategy),
                new VIZipCodeValidator(_strategy),
                new WFZipCodeValidator(_strategy),
                new XKZipCodeValidator(_strategy),
                new YTZipCodeValidator(_strategy),
                new YUZipCodeValidator(_strategy),
                new ZAZipCodeValidator(_strategy),
                new ZMZipCodeValidator(_strategy)
            };

            factory = new CountryZipCodeValidatorFactory(countryValidators);
        }
    }
}
